apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckluckmarket
  labels:
    app: duckluckmarket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duckluckmarket
  template:
    metadata:
      labels:
        app: duckluckmarket
    spec:
      containers:
        - name: auth-db
          image: redis
          imagePullPolicy: Always
        - name: auth-service
          image: duckluckmarket/auth-service:v1.7
          imagePullPolicy: Always
