apiVersion: v1
kind: Service
metadata:
  name: duckluckmarket
spec:
  type: LoadBalancer # ClusterIP, NodePort
  selector:
    app: duckluckmarket
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080