- name: "Install nginx"
  hosts: deploy
  become: yes
  tasks:
    - name: "Install nginx from apt"
      apt:
        name: nginx
        state: present
    - name: "Copy nginx config"
      copy:
        src: files/duckluckmarket.xyz.conf
        dest: /etc/nginx/conf.d
    - name: "Reload nginx configuration"
      command: nginx -s reload